addons:
  sonarcloud:
    organization: "step-project-final-1-twitter"
    token:
      secure: "g6Xr9te2J7F8JWsfNs2CXzFLS2FhpeIvCZF0OzKaqIz6bH1oah84WBr/cOqgNwDzNKasUaKcPQlA7tXqmLT8MqHDKANqURtTX5zBOg1oVQh20vbwYKlFGTjGZpMtIXRdUN5amwruSjRbToSTFdVflq69i6mndK9R5TMrrmsRWomypSxBdK1Dwl7kPb8/8sNNQeXfCHggl53Sjb9HsGIL1Yk3GZtGFAxfjCogHbjmATAcfBHWBmTwnbyemWwEZoitaS4NgaBbO+WRPOmX7gRo5oG+uzOT+qFJN5J7biYho6+E1oOHoEmgMgojwAZ/ycu4uxXQJcH2ofH+iG4VXbdJuMr4DMDMa0rXneaul13THWrZH2mzKHDytYdnuEApWDGt1rnsD8V3nTAt5rEh2+arYQ3UwklK5+HjOwDiXlYgAoRMNCeupgSMv0gAVwxPKALxzvfmOwOJFu6JnlTOD6jM/RceMc1OUiJTpTDzhxCWTKin69jvjxHhdY/eH/i5hNrOTIaRFzkCwbNY/aePpBE1PMinRQn+JCfwUhenVdH/bzPm84qf+dgExaVQOeAEkA4FCVdtx12f3xOwk0dsc+g4vA/pA5zKSSMzFiN+jYk0TwlCunjwk1oVh5H3184UtRk6+Ffk9Y3pwFDoQNwBKO+wNoL9GSemswF/+IAlNpl8DZA=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PavelBortnovskyi_Final_Step_Full_1
after_success:
  - mvn clean test jacoco:report coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}