spring:
  datasource:
    password: 111
    url: jdbc:h2:mem:testdb
    username: finaluser_1
    driver-classname: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: local
  url:
    server: http://localhost:8080
    client: http://localhost:3000
  mail:
    host: smtp.gmail.com
    port: 587
    username: fe8fs2finalstep@gmail.com
    password: vgrralowhzszavbs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #security:
    #oauth2:
      #client:
        #registration:
          #google:
            #client-id: 833649741221-eijh9fedi04psm4e9pfvu3atkbarj3bg.apps.googleusercontent.com
            #client-secret: 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
        #facebook:
        # client-id: <your client id>
        # client-secret: <your client secret>
jwt:
  secret: verySecretUniqueKey
  secretRefresh: wannaRefresh?
  secretPasswordReset: you_forgot_it_again!
  secretPasswordUpdate: ok_try_again!
  expiration: 7200000 #2h
  expirationRefresh: 604800000 #7d
  expirationPasswordReset: 86400000 #24h
  expirationPasswordUpdate: 3600000 #1h
  header: Authorization
cloudinary:
  cloudName: dojrbfnaz
  apiKey: 516471726946834
  apiSecret: JokricYXIJmtjF29Ptgm2H7FusA





